### ISSUE TITLE
Add release checklist

### ISSUE THREAD

**Issue by alancleary** [legumeinfo/jekyll-theme-legumeinfo#100]
Use the legumeinfo/web-components repo as a starting point

**Comment by svengato** [comment]
A few pedantic suggestions. Feel free to edit (or omit if they are too obvious) -

- Create a branch for the release. **Suggested branch name: release-vX.Y.Z**

- Bump the "version" number in package.json and reinstall the dependencies **(npm i)** so the correct version number is in package-lock.json.

- (following the above step) **Commit and push the release branch changes.**

**Comment by alancleary** [comment]
@svengato Did you mean to put this in the taxon-symbology repo? This repo doesn't have a `package.json` file or use npm...

**Comment by svengato** [comment]
Yes, I teleported into the wrong repository and will repost in taxon-symbology. Does each repository have a different checklist?

**Comment by alancleary** [comment]
> Does each repository have a different checklist?

Yes because they use different technologies and build processes.

**Comment by svengato** [comment]
Got it, thanks.

**Comment by svengato** [comment]
Moved to the [taxon-symbology](https://github.com/legumeinfo/taxon-symbology/issues/61) repository.

**Comment by alancleary** [comment]
Reopening because this issue hasn't been completed...

**Comment by alancleary** [comment]
Done in PR #105
