### ISSUE TITLE
Add alt text to site logo

### ISSUE THREAD

**Issue by nathanweeks** [legumeinfo/jekyll-theme-legumeinfo#102]
Could be based on the site title, or maybe just "site logo".

**Comment by alancleary** [comment]
I think "site logo" makes sense since that's what we call the image in the config. Speaking of the config, do you think it would be worth making this alt text configurable via the `_config.yml` file?

**Comment by nathanweeks** [comment]
From [this W3C example](https://www.w3.org/WAI/tutorials/images/functional/#example-1-image-used-alone-as-a-linked-logo), I guess might make sense to default to `alt="{{ site.title }} home"` instead?

I don't have a strong opinion on whether or not to allow the alt text for the site logo to be customized in `_config.yml`, or require the user to override `navbar.html` if they have a strong opinion on the alt text.
