### ISSUE TITLE
use of target="_blank" seems inconsistent

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/jekyll-theme-legumeinfo#15]
I'm personally not a big fan of not being in control of when a new window is opened; but if there's a compelling reason to have this style of link, then I'd argue we should be consistent about it. Right now, the tools menu on the left hand side seems to do this, while most other links do not (including the tools menu in the navbar). I could see a case for using this style when heading off to twitter or github (as is currently already being done in the navbar).

**Comment by sammyjava** [comment]
Yeah, we need to set a policy on new browser windows. My policy has been: if it links a different site, open a new window/tab. The Datastore is a different site, now on a new host: data.legumeinfo.org.

So I propose: use target="_blank" whenever the URL is absolute, not relative, meaning it's a different site.

I'll update all links according to what we decide is the rule. @cann0010  @nathanweeks chime in :)

**Comment by sammyjava** [comment]
As for creating a new tab on your own: research showed, at least when I was building websites for a living, that very few people are aware that they can do that, and, rather, simply click links. Given the general lack of tech skills amongst biologists, I'd guess that that is still true for the audience of legumeinfo.org. So I think we should assume that the user will just click a link, and from that decide whether we want it to open in a new tab.

**Comment by cann0010** [comment]
I'm OK with 'target="_blank"' for off-site links - though I also share some irritation with this behavior. 
At the Jekyll-soybase instance, we're trying to minimize the opening of new pages by incorporating some content into iframes. On the main branch (which is about a week behind the scannon branch), you can see this behavior at the tools menu: SequenceServer opens its content in an iframe. In the scannon branch, we've moved most of the tools and the CMap views into iframes - which @nathanweeks facilitated by adding a new full-width iframe layout.

**Comment by sammyjava** [comment]
Yer gonna have to work hard to convince me to use iframes on legumeinfo.org. That's a browser window in a browser window which is even worse than a new tab, IMO. For me, a core concept of legumeinfo.org is that it is a portal to other LIS web apps, not a site that pulls LIS web apps into iframes. It's clean and simple. Anyway, what I read was "I'm OK with 'target="_blank"' for off-site links" so I'll count you as a + vote on that policy. :) :)

**Comment by cann0010** [comment]
"I'll count you as a + vote on that policy" - That's fair.
As for iframes: I think it depends. Something like SequenceServer is essentially a web app without its own nav system, so it might as well be iframed. Similarly (more or less) for CMap and the genome browsers. The Mines and GCV - I take your point.

**Comment by sammyjava** [comment]
Oh, man, I just found this issue, which is on the theme, which I have nothing to do with, jekyll-legumeinfo is now on its own, with its design (there is no _themes directory) many, many changes downstream of the "starter" theme in this repo. Anyway, I checked, and the only use of "_blank" on jekyll-legumeinfo is for sites on different hosts. Note 1: the Datastore is on a different host. Note 2: all tools are on different hosts.

**Comment by sammyjava** [comment]
Given that you @adf-ncgr have the most tabs on your browser of any human on Earth, I don't think you're in the best position to argue this point. :) I'm gonna just sit on what I've coded and if there is a community outcry from the LIS group as a whole or actual users, if they exist, I'll update. It's already more of a mountain than a molehill. And this shouldn't be on the them repo, anyway. We can establish a policy change before launch and implement it.
