### ISSUE TITLE
Backport the blog

### ISSUE THREAD

**Issue by alancleary** [legumeinfo/jekyll-theme-legumeinfo#16]
For various reasons, the LIS Jekyll site no longer uses this theme. However, the structure and content of the LIS Jekyll site is still very much derived from this theme. A feature that was added to the LIS site that should also be included in the theme for the benefit of other groups is a blog. This is similar to the news and announcements, i.e. it should have its own (optional) card on the home page and designated page. Make it so!

**Comment by alancleary** [comment]
@sammyjava Can you tackle this now that you're bringing the LIS site back onto the theme?

**Comment by sammyjava** [comment]
Yup, will do.

**Comment by sammyjava** [comment]
It looks like announcements also needs to be added to the theme. I presume I'll reproduce the news parameters for announcements and blog with the usual blurb in the theme README:

- announcements_card: boolean
- announcements_card_item_limit: number
- blog_card: boolean
- blog_card_item_limit: number

**Comment by alancleary** [comment]
> It looks like announcements also needs to be added to the theme. I presume I'll reproduce the news parameters for announcements and blog with the usual blurb in the theme README:
> 
>     * announcements_card: boolean
> 
>     * announcements_card_item_limit: number
> 
>     * blog_card: boolean
> 
>     * blog_card_item_limit: number

Announcements were deprecated (PR #20); news should now be used for announcements. There's currently an issue in the jekyll-legumeinfo repo to integrate those changes: https://github.com/legumeinfo/jekyll-legumeinfo/issues/139

**Comment by alancleary** [comment]
> @alancleary relatedly (I think): How should uikit be referenced from the sites? Should there be a pointer to the css files that live in the theme - or is that necessary? At jekyll-soybase currently, we have the following:
> 
> ```
> find . -name uikit.min.css | grep -v git | grep -v _site
> ./_themes/jekyll-theme-legumeinfo/uikit/dist/css/uikit.min.css
> ./_themes/jekyll-theme-legumeinfo/assets/css/uikit.min.css
> ./assets/css/uikit.min.css
> ```

If you're using the theme then you don't need a copy of UIkit in your site's `assets/` directory and you don't have to explicitly reference UIkit anywhere, the theme will handle that for you.

**Comment by alancleary** [comment]
Done in PR #31.
