### ISSUE TITLE
Make global site font size configurable via theme

### ISSUE THREAD

**Issue by alancleary** [legumeinfo/jekyll-theme-legumeinfo#27]
Make it so and the tell @StevenCannon-USDA all about it.

**Comment by alancleary** [comment]
@StevenCannon-USDA The requested feature has been implemented in the configurable-font-size branch; the global font size can now be modified using the `style.font_size` variable in your site's `_config.yml` file. It looks like there's several other font sizes that this does not affect, so have a look and see if it's good enough or if we need to wrangle a few more.

**Comment by StevenCannon-USDA** [comment]
Thanks! That was quick. @maxglycine will also be happy to have this.

**Comment by alancleary** [comment]
Bumping this to see if @StevenCannon-USDA or @maxglycine had a chance to try it out.

**Comment by StevenCannon-USDA** [comment]
Not yet. Probably later this week, after I clear a few other things.

**Comment by sammyjava** [comment]
Just for grins I went extreme and set the font_size = 64px for demo purposes here in _config.yml:

# UIkit theme customization (sets colors, font size, etc.)
style:
     link_color: '#0071B3'
     link_hover_color: '#018fe2'
     global_muted_color: '#666'
     primary_background: '#87a96b'
     invert_navbar_text: true
     font_size: '64px'             <------------

which definitely worked:

https://jekyll.dev.lis.ncgr.org/

**Comment by maxglycine** [comment]
Could we also have the ability to choose the “font-family”?

**Comment by alancleary** [comment]
Thanks for setting up an example @sammyjava. It demonstrates that some of the font sizes aren't affected by the `$global-font-size` UIkit parameter that the `style.font_size` variable in the config file is bound to. Are you, @maxglycine, and @StevenCannon-USDA OK with this or do you want control over these other font sizes are well?

> Could we also have the ability to choose the “font-family”?

Yes. I'll push a commit that does that.

**Comment by alancleary** [comment]
The configurable-font-size branch has been updated so that the global font family can now be modified using the `style.font_family` variable in your site's `_config.yml` file. Similar to the font size feature, there's other font families in the site/theme that this does not affect. Let me know if you want control of those as well. Also, it's good to specify a series of fonts (via comma separated list) so that there's similar fonts to fallback to if one or more aren't present on the end-user's system; see the theme's `_config.yml` file for an example.

**Comment by maxglycine** [comment]
Fabulous!  Thanks so much!

**Comment by maxglycine** [comment]
That sounds good to me

**Comment by alancleary** [comment]
I apologize for the delay on this; I've been preoccupied with a grant proposal. Would someone else be willing to tackle this? Maybe @svengato?

**Comment by svengato** [comment]
I will look into this and estimate the workload.

**Comment by alancleary** [comment]
Thanks @svengato!

**Comment by svengato** [comment]
I checked out the **configurable-font-size** branch, and can update the font size and font family through `_config.yml`.

Just to confirm, is the goal to do the same for `global-small-font-size` through `global-2xlarge-font-size`, either by allowing the user to set each one by hand, or by automatically scaling them from the specified `font_size`? Does anyone strongly prefer one method over the other? I think automated scaling would be cool.

What about the "base" font sizes (for preformatted text like code samples)? We could scale these to `font_size` as well.

**Comment by svengato** [comment]
We also need default global font sizes for when the user does not specify `font_size`. I can restore that.

**Comment by alancleary** [comment]
> Just to confirm, is the goal to do the same for global-small-font-size through global-2xlarge-font-size, either by allowing the user to set each one by hand, or by automatically scaling them from the specified font_size? Does anyone strongly prefer one method over the other? I think automated scaling would be cool (otherwise one could make the "large" fonts smaller than the "small" ones).

Correct; we want to make the `global-small-font-size` through `global-2xlarge-font-size` configurable as well. I think by default these should scale relative to `global-font-size`, with the ratios being derived from what's currently in our theme. This means only `global-font-size` will need a default value, which is already being set in the theme's `_config.yml` and, thus, will be passed on to any site using the theme.

> What about the "base" font sizes (for preformatted text like code samples)? We could scale these to font_size as well.

I think for now we should limit it to the sizes we've already discussed. There's so many that going beyond these fundamental ones is a slippery slope!

**Comment by svengato** [comment]
Automatic font scaling tentatively works, using Liquid operations rather than Sass `calc()`.
```
{% assign fs = site.style.font_size | replace: "px", "" %}
$global-2xlarge-font-size: {{ fs | times: 2.5 }}px;
[...]
```

Next: handle case(s) where units are other than 'px'.

**Comment by alancleary** [comment]
> Automatic font scaling tentatively works, using Liquid operations rather than Sass `calc()`.
> 
> ```
> {% assign fs = site.style.font_size | replace: "px", "" %}
> $global-2xlarge-font-size: {{ fs | times: 2.5 }}px;
> [...]
> ```
> 
> Next: handle case(s) where units are other than 'px'.

Nice. It's pretty cool we can use Liquid in Sass.

**Comment by svengato** [comment]
Liquid **instead of** Sass.

**Comment by svengato** [comment]
On further investigation,

1. `calc()` is part of CSS, though there are Sass extensions. I prefer this approach over Liquid `times` because it automatically handles the units.

2. Unfortunately, it causes syntax errors which I traced to `uikit/src/scss/variables-theme.scss` not using `calc()` in lines like
```
$article-title-font-size: $article-title-font-size-m * 0.85 !default;
```
This should really be
```
$article-title-font-size: calc($article-title-font-size-m * 0.85) !default;
```
which works as expected. For now, we would have to make this correction everywhere we use uikit, but a long term solution would be to either make our own fork of uikit or submit a pull request.

3. The `!default` syntax seems to mean that default values exist, so I can remove the current ones (as @alancleary did for '15px' in commit 394c625db2cc6221b4d9f1c7b690f29031253925). In other words, you may ignore the "We also need default global font sizes" comment above.

4. According to `uikit/src/scss/variables-theme.scss`, the font scaling factors are
$global-2xlarge-font-size: 2.625
$global-xlarge-font-size: 2
$global-large-font-size: 1.5
$global-medium-font-size: 1.25
$global-small-font-size: 0.875
which slightly disagree with our current hard-coded font sizes, but I will stick with them.

**Comment by alancleary** [comment]
Done in PR #40.
