### ISSUE TITLE
Announcements under news may need news card revision

### ISSUE THREAD

**Issue by sammyjava** [legumeinfo/jekyll-theme-legumeinfo#32]
In blowing away the announcements on jekyll-legumeinfo:use-theme, I've put the announcements into news using "categories: announcements". But, you'll see that this makes the home page news card perhaps non-optimal (or maybe we're fine with it):

https://jekyll.dev.lis.ncgr.org/

If we're not fine with it, we'll need to tweak the theme's news card to present "general" and "announcements" news items separately. If we're fine with it, we'll just close this issue and crack open a beer (or other chosen beverage).

**Comment by alancleary** [comment]
What do you mean by non-optimal? Peanutbase has been using this model for a while. Perhaps @sdash-github or @nathanweeks can weigh in.

**Comment by sammyjava** [comment]
Just that it can hide the news because the top 3 items are all announcements. No big deal, just thought I'd mention it, I could see it being annoying down the line. But maybe it's fine.

**Comment by sammyjava** [comment]
It occurred to me because we have the (as yet unimplemented?) categories parameter in the news front matter. So then I thought that maybe we want to display the top N news (category: general) and top M announcements (category: announcements) on the card. But I'm probably thinking way too much for a Friday.

**Comment by alancleary** [comment]
Ah, that's right; categories! I think peanutbase has been using the simple solution; since we've deprecated announcements there is no longer an announcements category. News and announcements only differ in their content.

**Comment by alancleary** [comment]
I'm going close this issue. Feel free to re-open it if you feel like it hasn't been resolved.
