### ISSUE TITLE
Add GraphQL scripts

### ISSUE THREAD

**Issue by alancleary** [legumeinfo/jekyll-theme-legumeinfo#39]
The web-components library includes a `dev/` directory that demonstrates how to use the components. Specifically, it demonstrates how to load data from the LIS GraphQL server and shim it into structures compatible with the web components. This code has served as a template for the various sites that use the LIS Jekyll theme. For this reason, this JS code should be copied into the `assets/js/` directory of the theme AND DOCUMENTED. As with the web components, including these scripts in the head of a page should be opt-in via the page's Jekyll front matter so it's only loaded on pages that need it. Additionally, the URI of the GraphQL server should be configurable via the `_config.yml` file.

**Edit:** It's worth noting that the GraphQL query function underlying the specific queries uses the native `fetch` function. This function returns a promise so modifying the data being sent to a component to include links and whatnot is as simple as calling `.then()` on the returned promise and applying whatever modifications you want to the data.

**Comment by sammyjava** [comment]
Oh, I get it, because right now we have those scripts locally in the site, not theme:
```
[shokin@jekyll-dev-vm jekyll-legumeinfo]$ ls assets/js/graphql/
get-gene-form-data.js  get-genes.js  graphql.js  linkout-function.js
```

**Comment by sammyjava** [comment]
I can do this as part of the use-theme branch on the site (plus a new branch on the theme), shall I?

**Comment by alancleary** [comment]
That would be great. Thanks!

An implementation detail I didn't explicitly note above is that there should be an `assets/js/graphql/index.js` barrel so that adding the scripts to a Jekyll page is a matter of including that single file.

**Comment by sammyjava** [comment]
Alright, I'm new to barrels and don't see an example in web-components. Is the deal that I change, for example in graphql.js,
```function graphqlQuery(uri, query, variables={}, abortSignal=undefined) { ```
to
```export function graphqlQuery(uri, query, variables={}, abortSignal=undefined) { ```
and then in index.js I use
```import { graphqlQuery } from './graphql.js'```
???

**Comment by alancleary** [comment]
> Alright, I'm new to barrels and don't see an example in web-components. Is the deal that I change, for example in graphql.js, `function graphqlQuery(uri, query, variables={}, abortSignal=undefined) { ` to `export function graphqlQuery(uri, query, variables={}, abortSignal=undefined) { ` and then in index.js I use `import { graphqlQuery } from './graphql.js'` ???

Correct, the individual files will need to export their functions. `index.js`, however, will just re-export the contents of the other files:
```javascript
export * from './graphql.js';
```
When including the barrel in the page head you'll need to specify that it's a module:
```liquid
<script type="module" src="{{ "assets/js/graphql/index.js" | relative_url }}"></script>
```

**Comment by sammyjava** [comment]
Hrmph. The functions are not getting picked up. Here's my index.js and I put export in front of the functions and constants in the four js files. This includes the hack to get a _config.yml variable into a JS file. Maybe you know a better way, that's what I found.
```typescript
 ---
layout: blank
---
// query the LIS GraphQL server given by graphqluri in _config.yml.
// https://github.com/legumeinfo/graphql-server
// we can use system variables in a js file when we have front matter as above!
const uri = "{{ site.graphqluri }}"

export * from './graphql.js';
export * from './linkout-function.js';
export * from './get-gene-form-data.js';
export * from './get-genes.js';
```

**Comment by sammyjava** [comment]
I did check that the individual JS files are being read.

**Comment by alancleary** [comment]
> Hrmph. The functions are not getting picked up. Here's my index.js and I put export in front of the functions and constants in the four js files. This includes the hack to get a _config.yml variable into a JS file. Maybe you know a better way, that's what I found.
> 
> ```ts
>  ---
> layout: blank
> ---
> // query the LIS GraphQL server given by graphqluri in _config.yml.
> // https://github.com/legumeinfo/graphql-server
> // we can use system variables in a js file when we have front matter as above!
> const uri = "{{ site.graphqluri }}"
> 
> export * from './graphql.js';
> export * from './linkout-function.js';
> export * from './get-gene-form-data.js';
> export * from './get-genes.js';
> ```
What file is this in? The `graphql.js` file needs front matter to force evaluation of liquid template syntax but it shouldn't specify a layout. See the [`uikit-theme.scss`](https://github.com/legumeinfo/jekyll-theme-legumeinfo/blob/main/assets/css/uikit-theme.scss) file for an example.

**Comment by sammyjava** [comment]
Ah, OK, but that's not what's causing it to not work. (Before it just gave a warning that blank does not exist, so it's nice to not have that line). The issue remains: `Uncaught ReferenceError: getGeneFormData is not defined` so I'm doing something wrong in my chain-o-exports.

I've punched my changes into two new branches: jekyll-legumeinfo:graphql-js-in-theme and jekyll-theme-legumeinfo:assets-js-graphql. Hopefully it's obvious to you what I'm doing wrong here.

**Comment by sammyjava** [comment]
> > ```
> > 
> > ```
> 
> 
> What file is this in? The `graphql.js` file needs front matter to force evaluation of liquid template syntax but it shouldn't specify a layout. See the [`uikit-theme.scss`](https://github.com/legumeinfo/jekyll-theme-legumeinfo/blob/main/assets/css/uikit-theme.scss) file for an example.

Oh, yeah, that was in index.js. Moved to graphql.js.

**Comment by sammyjava** [comment]
Note: I don't think this is fatal, but simply having 
```
---
# This YAML front matter ensures Jekyll will pass the site variables in.
---
```
at the top of graphql.js leads to a boatload of HTML being put into `_site/assets/js/graphql/graphql.js` on the Jekyll site. Which is unattractive but perhaps not fatal. (I tried removing the above and hardcoding uri and still got the functions not being picked up by the gene search HTML.)

**Comment by sammyjava** [comment]
Just a gentle reminder @alancleary I'm still stumped as to why the site doesn't pick up the gene search functions from the theme's assets. I'm doing something wrong with my exports/imports, apparently. `jekyll-legumeinfo:graphql-js-in-theme` and `jekyll-theme-legumeinfo:assets-js-graphql`

**Comment by alancleary** [comment]
@sammyjava I don't know why having the empty YML front matter in a JS file would add a bunch of random HTML, and I wasn't able to replicate it either.

Regarding the import, I forgot that module content isn't added to the global scope (working with the web components library has muddied my memory!). So the import should actually be something like:
```liquid
{% if page.graphql %}
<script type="module">    
  import * as graphql from "{{ "assets/js/graphql/index.js" | relative_url }}";
  window.graphql = graphql;
</script>
{% endif %}
```
This takes all of the GraphQL code and sticks it in the global `graphql` variable. Since all of the exported functions are now going to be accessed via this variable, it probably makes sense to rename the `graphqlQuery` function to just `query` so calling it will become `graphql.query(...)` instead of `graphql.graphqlQuery(...)`.

**Comment by sammyjava** [comment]
Ok, this is a bit messy (to me). assets/js/graphql/index.js exports FOUR files:
```
export * from './graphql.js';
export * from './linkout-function.js';
export * from './get-gene-form-data.js';
export * from './get-genes.js';
```
Those files contain references to themselves, for example `linkout-function.js` references the function formerly known as `graphqlQuery` now `query` which was defined in `graphql.js`. So presumably now that it's `query` I reference it in `linkout-function.js` as just `query`, right?

That being said, `graphql` is not being defined with the following code:
```
---
layout: full-width
title: Gene Search
web_components: true
graphql: true
---

{% if page.graphql %}
<script type="module">
  import * as graphql from "{{ 'assets/js/graphql/index.js' | relative_url }}";
  window.graphql = graphql;
</script>
{% endif %}
```

I get `Uncaught ReferenceError: graphql is not defined`. However, the JS files are indeed being loaded. (And I checked by removing the page.graphql conditional, same result.)

**Comment by sammyjava** [comment]
That Uncaught Reference Error occurs here:
```
      const geneSearchElement = document.getElementById('gene-search');
      geneSearchElement.formDataFunction = graphql.getGeneFormData;
```

**Comment by alancleary** [comment]
At this point I think it would be more productive for me to just implement this. Thanks for trying!

**Comment by sammyjava** [comment]
Yup, I agree and will look most eagerly at the implementation. :) I'll delete my branches.

**Comment by alancleary** [comment]
@sammyjava I added the GraphQL scripts in the graphql-scripts branch. Interestingly I ended up using an [import map](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script/type/importmap) to make the JavaScript module available in `<script>` tags that will be used to configure web components. There are other ways to do this but import maps seemed to reliably get the scripts loaded in time for the components to automatically search if query string parameters are present.

I'm going to hold off on opening a PR since the imminent [trait association search component](https://github.com/legumeinfo/web-components/pull/212) will require more GraphQL code. In the meantime free to take it for a spin and let me know what you think.

**Comment by sammyjava** [comment]
I'm wondering why it's always loaded in head.html rather than having a page.graphql conditional.

**Comment by sammyjava** [comment]
And why did you not include the linkout function, which is also a graphql query? Forgot it, perhaps?

**Comment by alancleary** [comment]
> I'm wondering why it's always loaded in head.html rather than having a page.graphql conditional.

The import map maps the import path to the `lis-graphql` JavaScript module but the code isn't actually loaded until the module is used, i.e. something is imported from the module. So I decided not to introduce an opt-in front matter variable since having the import map there when you're not using the module has virtually no overhead.

> And why did you not include the linkout function, which is also a graphql query? Forgot it, perhaps?

I sure did. I'll be sure to include it before opening a PR.

**Comment by sammyjava** [comment]
FWIW I'm still having trouble getting functions resolved, but I'm probably not running the right code on the calling side.
```
Uncaught (in promise) Error: No form data function provided
Uncaught (in promise) Error: No search function provided
```
Also, `query.js` is still getting all the HTML stuffed in front on the dev site (unlike in your case, apparently) due to the empty front matter. I wonder if there's some _config difference on the dev site I'm running. If I yank the front matter and hardcode `url` in `query.js` the HTML goes away and I don't get the error about the unexpected ">" in `query.js`. I'd like to figure that out, it's pretty messy.

**Comment by sammyjava** [comment]
Ahhh interesting, testing on my older setup. Recall that I had
---
layout: blank
---
```
That DID NOT insert HTML into the page. But if I have EMPTY front matter:
```
---
## empty front matter
---
```
I reproduce the HTML getting stuffed in with the Uncaught SyntaxError: expected expression, got '<' error.

Recall that I had gotten the "layout: blank" trip from the interwebs. It seems to prevent the HTML from getting in there. Perhaps we have different default layouts? If the default were blank, you'd be able to use empty front matter.

**Comment by alancleary** [comment]
This sounds like an environment/jekyll-legumeinfo issue. The theme provides a default layout, i.e. `_layouts/default.html`, and it has never interfered with anything, such as the UIkit SCSS theme which is also using empty front matter. I develop the theme as a submodule of jekyll-starter-legumeinfo and run the site with Docker so the environment is consistent and reproducible. The only issue I tend to have is Firefox caching stuff in the theme but that's easy enough to work around.

**Comment by sammyjava** [comment]
Should I not have the default layout set in _config.yml as follows? Not sure what else in the enviro is an issue, but I'm not going to worry about it, I don't think it's a fatal error.
```
# Site-wide defaults
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: "blog/"
      type: "posts"
    values:
      layout: "blog-item"
  -
    scope:
      path: "news/"
      type: "posts"
    values:
      layout: "news-item"
```

**Comment by sammyjava** [comment]
Ah yes the starter site does NOT have that stuff in _config.yml (and neither does the theme).

**Comment by alancleary** [comment]
> Should I not have the default layout set in _config.yml as follows?

The default entry is redundant with the theme and since it doesn't specify a [`type` for the `scope`](https://jekyllrb.com/docs/configuration/front-matter-defaults/) it's being applied to everything that's not under `blog/` or `news/`, including SCSS and JS files under `assets/` that have front matter.

**Comment by sammyjava** [comment]
So, back to this. I've fixed the issue with HTML being spit out with the JS file. And this seems to be _working_  fine, running my  graphql-js-in-theme branch of jekyll-legumeinfo against the graphql-scripts branch of jekyll-theme-legumeinfo.

However, and this is probably OCD, I still get error messages in the console:
```
Uncaught ReferenceError: graphql is not defined
    <anonymous> https://jekyll.dev.lis.ncgr.org/tools/search/gene.html?page=1&genus=&species=&strain=&identifier=&description=photosynthesis&family=:685
[gene.html:685:7](https://jekyll.dev.lis.ncgr.org/tools/search/gene.html?page=1&genus=&species=&strain=&identifier=&description=photosynthesis&family=)
Uncaught (in promise) Error: No form data function provided
    formDataFunction https://cdn.jsdelivr.net/npm/@legumeinfo/web-components@1.0.0/dist/web-components.min.js:145
```
Is this due to a race condition, the web-components tag being read before the JS module is fully loaded? Do we care if it works?

I'd like to get all this stuff (theme, LIS site) merged into main soon, along with getting graphql-server:5.1.0.3 merged in as I'm about ready to promote GlycineMine and LegumeMine.

**Comment by sammyjava** [comment]
BTW as you'd expect, those errors are only thrown during initial page load, not during subsequent searches.

**Comment by sammyjava** [comment]
As far as I know, the thing left on this issue is to add the linkouts code to the theme. Unless you think that quick flash of the pink error box on the page as the code loads is an issue (I suppose it is, but that sure seems tricky to solve!).

**Comment by alancleary** [comment]
It looks like you haven't updated legumeinfo to use the syntax I [documented in the README](https://github.com/legumeinfo/jekyll-theme-legumeinfo/tree/graphql-scripts#web-components). Maybe try that?

**Comment by sammyjava** [comment]
No, I did. Here, I'll commit it for your viewing pleasure.

https://github.com/legumeinfo/jekyll-legumeinfo/blob/graphql-js-in-theme/tools/search/gene.html

It's working fine (other than the pink box flash) but I'm not getting links on the gene results. And I don't see the linkouts code under `jekyll-legumeinfo/_themes/jekyll-theme-legumeinfo/assets/js`.

**Comment by alancleary** [comment]
So I should disregard the error you reported an hour ago? If I follow the link in that error message the code is clearly not up to date...

I still need to add the linkout code. Probably won't get to it until next week. Feel free to tackle it if that's not soon enough.

**Comment by sammyjava** [comment]
> So I should disregard the error you reported an hour ago? If I follow the link in that error message the code is clearly not up to date...

Yeah, I had left the old script tag underneath the new module import which was throwing the `graphql is not defined`. :) Sorry about that!

But I do still get the initial error `Uncaught (in promise) Error: No form data function provided` on a fresh page load which is resolved in a fraction of second (here at work at least) and the form data function is fine.

https://jekyll.dev.lis.ncgr.org/tools/search/gene.html

You have to look very carefully to see the red "Failed to load data" error flash on the page, perhaps it lasts longer on a slow connection. Unless there's something else I should be doing but I just copied the code chunk from the current `graphql-scripts` README.

**Comment by sammyjava** [comment]
> I still need to add the linkout code. Probably won't get to it until next week. Feel free to tackle it if that's not soon enough.

I'll give it a try, once I have examples like you've provided in `/assets/js/graphql` I can usually sally forth.

**Comment by alancleary** [comment]
> I do still get the initial error Uncaught (in promise) Error: No form data function provided on a fresh page load which is resolved in a fraction of second (here at work at least) and the form data function is fine.

That's a harmless bug in the gene search component. Apparently giving the form data function property a default value triggers [the auto-search code](https://github.com/legumeinfo/web-components/blob/main/src/lis-gene-search-element.ts#L302), which is ironic because the default function throws the error you're seeing :upside_down_face:

**Comment by sammyjava** [comment]
Well, I thought adding the linkouts would be straightforward, but I failed. No problem importing the linkoutFunction as far as I know, and no new errors, but I'm not getting any a tags in the results. Here's my gene.html:
```html
---
layout: full-width
title: Gene Search
web_components: true
---

<lis-gene-search-element id="gene-search"></lis-gene-search-element>
<lis-modal-element modalId="modal">
  <lis-linkout-element id="linkouts"></lis-linkout-element>
</lis-modal-element>

<script type="module">
  import {getOrganismsFormData, geneSearch, linkoutFunction} from "lis-graphql";
  const geneSearchElement = document.getElementById('gene-search');
  geneSearchElement.formDataFunction = getOrganismsFormData;
  geneSearchElement.searchFunction = geneSearch;
  const linkoutElement = document.getElementById('linkouts');
  linkoutElement.linkoutFunction = linkoutFunction;
  // wait for the modal slot to load before adding an event listener
  window.onload = (event) => {
      const modal = document.getElementById('modal');
      modal.addEventListener('toggle', (event) => {
          const [{$el: link}, ...uikitComponents] = event.detail;
          const {gene, location, start, end} = link.dataset;
          let type = '';
          let variables = {};
          if (gene !== undefined) {
              type = 'gene';
              variables = {identifier: gene};
          } else if (location !== undefined && start !== undefined && end !== undefined) {
              type = 'location';
              variables = {identifier: location, start: parseInt(start), end: parseInt(end)};
          }
          linkoutElement.getLinkouts({type, variables});
      });
  }
</script>
```

**Comment by sammyjava** [comment]
OK, I get it, never mind, the LINKS themselves are not implemented in `get-genes.js` so that's why the results aren't linked. I need to add something akin to https://github.com/legumeinfo/jekyll-legumeinfo/blob/6f8374feca6fe8371ca86078f3285367d165e90c/assets/js/graphql/get-genes.js#L68C1-L73C32

**Comment by alancleary** [comment]
I just realized I should clarify that I'm working on this now since you weren't at the stand-up this morning.

Combing modals with linkouts and having them shown when a gene or location is clicked is a pretty specific use-case for the gene search component. So while I think we should provide as many pre-programmed pieces of this recipe as possible, I don't think it should actually be the preprogrammed behavior of the `geneSearch` function provided by the `lis-graphql` scripts in the theme. If we do it right, though, putting the pieces together to achieve that functionality should be easy.

**Comment by sammyjava** [comment]
Yup, I gave up on Friday after committing what I'd done and making that comment on the commit. I'll be interested to see how close I got. :)

**Comment by alancleary** [comment]
Closing since we can't properly support the trait association search until the next Intermine release. I'll open a different, more specific issue for those scripts.
