### ISSUE TITLE
do we need to maintain the example _data in future

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/jekyll-theme-legumeinfo#42]
see discussion about its initial raision d'etre here:
https://github.com/legumeinfo/jekyll-theme-legumeinfo/pull/22#issuecomment-1800619995

**Comment by adf-ncgr** [comment]
sounds like @sammyjava and @alancleary may have already decided this one:
https://github.com/legumeinfo/jekyll-theme-legumeinfo/pull/22#issuecomment-1802337779
but @nathanweeks should feel free to comment in case he disagrees

**Comment by nathanweeks** [comment]
> sounds like @sammyjava and @alancleary may have already decided this one: [#22 (comment)](https://github.com/legumeinfo/jekyll-theme-legumeinfo/pull/22#issuecomment-1802337779) but @nathanweeks should feel free to comment in case he disagrees

I agree that _data should go in the starter instead of the theme.

**Comment by adf-ncgr** [comment]
great thanks- just submitted the unanimous opinion of the court under #43
