### ISSUE TITLE
Add file_exists gem to theme

### ISSUE THREAD

**Issue by sammyjava** [legumeinfo/jekyll-theme-legumeinfo#44]
I added the file_exists gem to the theme (and removed it from jekyll-legumeinfo:use-theme) and got this result, which I know I can fix but I wonder if I did something wrong in the Gemfile:
```console
[shokin@jekyll-dev-vm jekyll-theme-legumeinfo]$ bundle install
Fetching https://github.com/asperduti/jekyll_file_exists.git
Git error: command `git rev-parse --abbrev-ref HEAD` in directory /usr/share/gems/cache/bundler/git/jekyll_file_exists-2183fbd087f5eca0d62dc763498354e08667d54f has failed.
fatal: detected dubious ownership in repository at '/usr/share/gems/cache/bundler/git/jekyll_file_exists-2183fbd087f5eca0d62dc763498354e08667d54f'
To add an exception for this directory, call:

	git config --global --add safe.directory /usr/share/gems/cache/bundler/git/jekyll_file_exists-2183fbd087f5eca0d62dc763498354e08667d54f
```
Dubious ownership indeed! Here's the Gemfile:
```
# frozen_string_literal: true

source "https://rubygems.org"
gemspec

## handy way to see if an image exists on the site
gem 'jekyll_file_exists', :git => 'https://github.com/asperduti/jekyll_file_exists.git'
```

**Comment by sammyjava** [comment]
(I don't recall having to add exceptions for Gem directories before, but maybe I have.)

**Comment by sammyjava** [comment]
Although I don't recall running `bundle install` in the theme either. But I got an error on the site when I started it up after moving `file_exists`.

**Comment by sammyjava** [comment]
OK reopening because I get the error now with file_exists in the theme. Seems the main site isn't picking it up.
```console
  Liquid Exception: Liquid syntax error (line 39): Unknown tag 'file_exists' in taxa/arachis/index.html
```

**Comment by sammyjava** [comment]
Tell ya what, I'll bounce this update over to you. :) I'll yank `file_exists` from `jekyll-legumeinfo:use-theme` to test your theme update. :)

**Comment by alancleary** [comment]
Done in PR #45.
