### ISSUE TITLE
Rename repository

### ISSUE THREAD

**Issue by alancleary** [legumeinfo/jekyll-theme-legumeinfo#6]
I've noticed that Jekyll themes seems to have a naming convention: jekyll-theme-<theme name>. So perhaps we should fall in line and rename this repo "jekyll-theme-legumeinfo" or something similar. Suggestions are welcome.

**Comment by adf-ncgr** [comment]
I like "jekyll-theme-legumeinfo". No need for creativity here.

**Comment by alancleary** [comment]
Done via GitHub settings and in commit 3db7d6c09a28ad35ad539a3d0029042cd3600510 of site repo.
